In [1]:
import mlflow
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

csv_url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = pd.read_csv(csv_url, sep=";")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [2]:
train, test = train_test_split(data)
train_x = train.drop(["quality"], axis=1)
test_x = test.drop(["quality"], axis=1)
train_y = train[["quality"]]
test_y = test[["quality"]]
train_x, test_x, train_y, test_y

(      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 381            13.7             0.415         0.68             2.9      0.085
 1316            5.4             0.740         0.00             1.2      0.041
 868             6.8             0.560         0.22             1.8      0.074
 1246            7.4             0.740         0.07             1.7      0.086
 485            10.2             0.670         0.39             1.9      0.054
 ...             ...               ...          ...             ...        ...
 442            15.6             0.685         0.76             3.7      0.100
 1233           10.2             0.230         0.37             2.2      0.057
 429            12.8             0.840         0.63             2.4      0.088
 1060           11.6             0.230         0.57             1.8      0.074
 460             9.2             0.430         0.52             2.3      0.083

       free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
 381                  17.0                  43.0  1.00140  3.06       0.80
 1316                 16.0                  46.0  0.99258  4.01       0.59
 868                  15.0                  24.0  0.99438  3.40       0.82
 1246                 15.0                  48.0  0.99502  3.12       0.48
 485                   6.0                  17.0  0.99760  3.17       0.47
 ...                   ...                   ...      ...   ...        ...
 442                   6.0                  43.0  1.00320  2.95       0.68
 1233                 14.0                  36.0  0.99614  3.23       0.49
 429                  13.0                  35.0  0.99970  3.10       0.60
 1060                  3.0                   8.0  0.99810  3.14       0.70
 460                  14.0                  23.0  0.99760  3.35       0.61

       alcohol
 381      10.0
 1316     12.5
 868      11.2
 1246     10.0
 485      10.0
 ...       ...
 442      11.2
 1233      9.3
 429      10.4
 1060      9.9
 460      11.3

 [1199 rows x 11 columns],
       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 19              7.9             0.320         0.51             1.8      0.341
 493             8.7             0.690         0.31             3.0      0.086
 455            11.3             0.620         0.67             5.2      0.086
 1308            9.7             0.690         0.32             2.5      0.088
 438            10.4             0.410         0.55             3.2      0.076
 ...             ...               ...          ...             ...        ...
 1149           10.0             0.350         0.47             2.0      0.061
 217             8.1             0.725         0.22             2.2      0.072
 447             9.3             0.480         0.29             2.1      0.127
 400             6.6             0.735         0.02             7.9      0.122
 777             6.9             0.635         0.17             2.4      0.241

       free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
 19                   17.0                  56.0  0.99690  3.04       1.08
 493                  23.0                  81.0  1.00020  3.48       0.74
 455                   6.0                  19.0  0.99880  3.22       0.69
 1308                 22.0                  91.0  0.99790  3.29       0.62
 438                  22.0                  54.0  0.99960  3.15       0.89
 ...                   ...                   ...      ...   ...        ...
 1149                  6.0                  11.0  0.99585  3.23       0.52
 217                  11.0                  41.0  0.99670  3.36       0.55
 447                   6.0                  16.0  0.99680  3.22       0.72
 400                  68.0                 124.0  0.99940  3.47       0.53
 777                   6.0                  18.0  0.99610  3.40       0.59

       alcohol
 19        9.2
 493      11.6
 455      13.4
 1308     10.1
 438       9.9
 ...       ...
 1149     12.0
 217       9.1
 447      11.2
 400       9.9
 777      10.3

 [400 rows x 11 columns],
       quality
 381         6
 1316        6
 868         6
 1246        5
 485         5
 ...       ...
 442         7
 1233        4
 429         6
 1060        6
 460         6

 [1199 rows x 1 columns],
       quality
 19          6
 493         6
 455         8
 1308        5
 438         6
 ...       ...
 1149        6
 217         5
 447         5
 400         5
 777         6

 [400 rows x 1 columns])

In [3]:
def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    r2 = r2_score(actual, pred)
    return rmse, mae, r2
# Parameters
alpha = 0.5
l1_ratio = 0.5
# Execute ElasticNet
lr = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42)
lr.fit(train_x, train_y)
# Evaluate Metrics
predicted_qualities = lr.predict(test_x)
(rmse, mae, r2) = eval_metrics(test_y, predicted_qualities)
# Print out metrics
print("Elasticnet model (alpha=%f, l1_ratio=%f):" % (alpha, l1_ratio))
print("  RMSE: %s" % rmse)
print("  MAE: %s" % mae)
print("  R2: %s" % r2)

Elasticnet model (alpha=0.500000, l1_ratio=0.500000):
  RMSE: 0.7274192805429398
  MAE: 0.6014619988593539
  R2: 0.14232244073206324

In [ ]:
# MLflow
mlflow.set_experiment("test")
try:
    mlflow.create_experiment("test", artifact_location="s3://mlflow")
except:
    pass
with mlflow.start_run():
    mlflow.log_param("alpha", alpha)
    mlflow.log_param("l1_ratio", l1_ratio)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2", r2)
    mlflow.log_metric("mae", mae)
    mlflow.sklearn.log_model(lr, "model")
    mlflow.log_artifact("wine-quality")